spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#jwt:
#  secret: your-super-secret-key
#  expirationMs: 3600000


  